In [1]:
import pandas as pd

In [2]:
games = pd.read_csv("Video Games Dataset.csv")

In [3]:
games.head(10)

,Rank,Name,Platform,Year,Genre,Publisher,NorthAmerica_Sales,EurpeanUnion_Sales,Japan_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,NaN,12.88,3.79,NaN,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,NaN,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,6,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,NaN
6,7,New Super Mario Bros.,DS,2006,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
7,8,Wii Play,Wii,2006,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
8,9,New Super Mario Bros. Wii,Wii,2009,Platform,Nintendo,14.59,7.06,NaN,2.26,28.62
9,10,Duck Hunt,NES,1984,Shooter,Nintendo,26.93,NaN,0.28,0.47,28.31

Number of Rows and Columns

In [4]:
games.info()
# 199 rows, 11 columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                199 non-null    int64
 1   Name                199 non-null    object
 2   Platform            199 non-null    object
 3   Year                199 non-null    int64
 4   Genre               199 non-null    object
 5   Publisher           198 non-null    object
 6   NorthAmerica_Sales  185 non-null    float64
 7   EurpeanUnion_Sales  190 non-null    float64
 8   Japan_Sales         189 non-null    float64
 9   Other_Sales         192 non-null    float64
 10  Global_Sales        187 non-null    float64
dtypes: float64(5), int64(2), object(4)
memory usage: 17.2+ KB

How many games have Wii as their platform

In [5]:
len(games[games['Platform'] == "Wii"])

21

Top 10 Publishers

In [6]:
games["Publisher"].value_counts().head(10)

Nintendo                       83
Activision                     23
Sony Computer Entertainment    17
Microsoft Game Studios         15
Electronic Arts                12
Take-Two Interactive           10
Ubisoft                         9
Capcom                          4
Bethesda Softworks              4
Sega                            3
Name: Publisher, dtype: int64

Top Game Genres

In [7]:
games["Genre"].value_counts().head(10)

Action          37
Shooter         34
Platform        30
Role-Playing    28
Sports          15
Racing          14
Misc            13
Fighting         8
Simulation       7
Puzzle           7
Name: Genre, dtype: int64

Top 20 Nintendo Games

In [8]:
games[games["Publisher"] == "Nintendo"].head(20)

,Rank,Name,Platform,Year,Genre,Publisher,NorthAmerica_Sales,EurpeanUnion_Sales,Japan_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,NaN,12.88,3.79,NaN,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,NaN,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,6,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,NaN
6,7,New Super Mario Bros.,DS,2006,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
7,8,Wii Play,Wii,2006,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
8,9,New Super Mario Bros. Wii,Wii,2009,Platform,Nintendo,14.59,7.06,NaN,2.26,28.62
9,10,Duck Hunt,NES,1984,Shooter,Nintendo,26.93,NaN,0.28,0.47,28.31
10,11,Nintendogs,DS,2005,Simulation,Nintendo,9.07,11.00,1.93,2.75,24.76
11,12,Mario Kart DS,DS,2005,Racing,Nintendo,9.81,7.57,4.13,1.92,23.42
12,13,Pokemon Gold/Pokemon Silver,GB,1999,Role-Playing,Nintendo,NaN,6.18,7.20,0.71,23.10
13,14,Wii Fit,Wii,2007,Sports,Nintendo,8.94,8.03,3.60,2.15,NaN
14,15,Wii Fit Plus,Wii,2009,Sports,Nintendo,9.09,8.59,2.53,1.79,22.00
17,19,Super Mario World,SNES,1990,Platform,Nintendo,12.78,NaN,3.54,0.55,20.61
18,20,Brain Age: Train Your Brain in Minutes a Day,DS,2005,Misc,Nintendo,4.75,9.26,NaN,2.05,20.22
19,21,Pokemon Diamond/Pokemon Pearl,DS,2006,Role-Playing,Nintendo,6.42,4.52,6.04,1.37,18.36
20,22,Super Mario Land,GB,1989,Platform,Nintendo,NaN,2.71,4.18,0.42,18.14
21,23,Super Mario Bros. 3,NES,1988,Platform,Nintendo,9.54,3.44,3.84,0.46,17.28

Top 10 Genres in Nintendo

In [9]:
games[games["Publisher"] == "Nintendo"]["Genre"].value_counts().head(10)

Platform        24
Role-Playing    15
Racing           9
Misc             7
Puzzle           6
Fighting         5
Sports           4
Action           4
Simulation       4
Shooter          3
Name: Genre, dtype: int64

Top Sports Games

In [10]:
games[games["Genre"] == "Sports"]

,Rank,Name,Platform,Year,Genre,Publisher,NorthAmerica_Sales,EurpeanUnion_Sales,Japan_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,NaN,2.96,33.00
13,14,Wii Fit,Wii,2007,Sports,Nintendo,8.94,8.03,3.60,2.15,NaN
14,15,Wii Fit Plus,Wii,2009,Sports,Nintendo,9.09,8.59,2.53,1.79,22.00
72,78,FIFA 16,PS4,2015,Sports,Electronic Arts,1.11,6.06,0.06,1.26,8.49
80,86,Mario & Sonic at the Olympic Games,Wii,2007,Sports,Sega,2.58,3.90,0.66,0.91,8.06
106,118,Zumba Fitness,Wii,2010,Sports,505 Games,3.50,2.64,0.00,0.67,NaN
110,122,FIFA 12,PS3,2011,Sports,Electronic Arts,0.84,4.32,0.11,1.42,6.69
113,125,FIFA 15,PS4,2014,Sports,Electronic Arts,0.79,4.29,0.05,1.47,6.59
127,140,Kinect Sports,X360,2010,Sports,Microsoft Game Studios,3.92,1.78,0.03,0.51,6.24
168,190,Mario & Sonic at the Olympic Games,DS,2008,Sports,Sega,1.64,2.48,0.44,0.58,5.14
176,200,FIFA Soccer 11,PS3,2010,Sports,Electronic Arts,0.60,3.29,0.06,1.13,5.08
179,203,Tony Hawk's Pro Skater,PS,1999,Sports,Activision,3.42,1.38,0.02,0.20,5.02
194,220,FIFA 15,PS3,2014,Sports,Electronic Arts,0.57,3.14,0.04,1.07,4.82
196,222,FIFA 17,PS4,2016,Sports,Electronic Arts,0.28,3.75,0.06,0.69,4.77

Top 10 Game Platforms

In [11]:
games["Platform"].value_counts().head(10)

PS3     31
X360    30
Wii     21
PS      20
DS      20
GB      11
PS4      9
N64      8
3DS      8
GBA      7
Name: Platform, dtype: int64

Top 20 PS3 and PS4 Games

In [12]:
games[(games["Platform"] == "PS3") | (games["Platform"] == "PS4") ].head(20)

,Rank,Name,Platform,Year,Genre,Publisher,NorthAmerica_Sales,EurpeanUnion_Sales,Japan_Sales,Other_Sales,Global_Sales
16,17,Grand Theft Auto V,PS3,2013,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
30,34,Call of Duty: Black Ops 3,PS4,2015,Shooter,Activision,NaN,5.81,0.35,2.31,14.24
31,35,Call of Duty: Black Ops II,PS3,2012,Shooter,Activision,4.99,5.88,0.65,2.52,14.03
34,38,Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,5.54,5.82,0.49,1.62,13.46
36,41,Call of Duty: Black Ops,PS3,2010,Shooter,Activision,5.98,4.44,0.48,1.83,12.73
40,45,Grand Theft Auto V,PS4,2014,Action,Take-Two Interactive,3.80,5.81,0.36,2.02,11.98
49,55,Gran Turismo 5,PS3,2010,Racing,Sony Computer Entertainment,2.96,4.88,0.81,2.12,10.77
50,56,Call of Duty: Modern Warfare 2,PS3,2009,Shooter,Activision,4.99,3.69,0.38,1.63,10.69
51,57,Grand Theft Auto IV,PS3,2008,Action,Take-Two Interactive,4.76,3.76,0.44,1.62,10.57
62,68,Call of Duty: Ghosts,PS3,2013,Shooter,Activision,4.09,3.73,0.38,1.38,9.59
72,78,FIFA 16,PS4,2015,Sports,Electronic Arts,1.11,6.06,0.06,1.26,8.49
77,83,FIFA Soccer 13,PS3,2012,Action,Electronic Arts,1.06,5.05,0.13,2.01,8.24
86,93,Star Wars Battlefront (2015),PS4,2015,Shooter,Electronic Arts,2.93,3.29,NaN,1.23,7.67
87,94,Call of Duty: Advanced Warfare,PS4,2014,Shooter,Activision,2.80,3.30,0.14,1.37,7.60
97,104,Battlefield 3,PS3,2011,Shooter,Electronic Arts,2.85,2.93,0.35,1.10,7.23
102,110,Fallout 4,PS4,2015,Role-Playing,Bethesda Softworks,2.47,3.15,0.24,1.10,6.96
104,116,Uncharted 3: Drake's Deception,PS3,2011,Action,Sony Computer Entertainment,2.77,2.80,0.19,1.06,6.83
108,120,Uncharted 2: Among Thieves,PS3,2009,Action,Sony Computer Entertainment,3.27,2.25,0.21,1.00,6.73
109,121,Call of Duty 4: Modern Warfare,PS3,2007,Shooter,Activision,3.10,2.30,0.28,1.04,6.72
110,122,FIFA 12,PS3,2011,Sports,Electronic Arts,0.84,4.32,0.11,1.42,6.69

Top 10 Xbox Games

In [13]:
games[games["Platform"] == "X360"].head(10)

,Rank,Name,Platform,Year,Genre,Publisher,NorthAmerica_Sales,EurpeanUnion_Sales,Japan_Sales,Other_Sales,Global_Sales
15,16,Kinect Adventures!,X360,2010,Misc,Microsoft Game Studios,14.97,4.94,0.24,1.67,NaN
22,24,Grand Theft Auto V,X360,2013,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38
26,30,Call of Duty: Modern Warfare 3,X360,2011,Shooter,Activision,9.03,4.28,0.13,1.32,14.76
28,32,Call of Duty: Black Ops,X360,2010,Shooter,Activision,9.67,3.73,0.11,1.13,14.64
32,36,Call of Duty: Black Ops II,X360,2012,Shooter,Activision,8.25,4.30,0.07,1.12,13.73
33,37,Call of Duty: Modern Warfare 2,X360,2009,Shooter,Activision,8.52,3.63,0.08,1.29,13.51
39,44,Halo 3,X360,2007,Shooter,Microsoft Game Studios,7.97,2.83,0.13,1.21,NaN
46,52,Grand Theft Auto IV,X360,2008,Action,Take-Two Interactive,6.76,3.10,0.14,1.03,11.02
56,62,Call of Duty: Ghosts,X360,2013,Shooter,Activision,NaN,2.63,0.04,0.82,10.21
57,63,Halo: Reach,X360,2010,Shooter,Microsoft Game Studios,7.03,NaN,0.08,0.78,9.88

Higest Global Sales

In [14]:
games["Global_Sales"].max()

82.74

Lowest Global Sales

In [15]:
games["Global_Sales"].min()

4.76

Higest North American Sales

In [16]:
games["NorthAmerica_Sales"].max()

41.49

Lowest North American Sales

In [17]:
games["NorthAmerica_Sales"].min()
# games[games["NorthAmerica_Sales"] == 0]

0.0

Highest Other Sales

In [18]:
games["Other_Sales"].max()
# games[games["Other_Sales"] == 8.46]

8.46

Lowest Other Sales

In [19]:
games["Other_Sales"].min()
# games[games["Other_Sales"] == 0]

0.0

GTA Games

In [20]:
def df_searcher(game_name, name):
    if game_name in name.lower():
        return True
    else:
        return False

In [32]:
gta_games = games[games["Name"].apply(lambda x: df_searcher("grand", x))]
gta_games

,Rank,Name,Platform,Year,Genre,Publisher,NorthAmerica_Sales,EurpeanUnion_Sales,Japan_Sales,Other_Sales,Global_Sales
16,17,Grand Theft Auto V,PS3,2013,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
22,24,Grand Theft Auto V,X360,2013,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38
40,45,Grand Theft Auto V,PS4,2014,Action,Take-Two Interactive,3.80,5.81,0.36,2.02,11.98
46,52,Grand Theft Auto IV,X360,2008,Action,Take-Two Interactive,6.76,3.10,0.14,1.03,11.02
51,57,Grand Theft Auto IV,PS3,2008,Action,Take-Two Interactive,4.76,3.76,0.44,1.62,10.57
84,91,Grand Theft Auto: Liberty City Stories,PSP,2005,Action,Take-Two Interactive,2.90,2.83,0.24,1.75,7.72
174,198,Grand Theft Auto V,XOne,2014,Action,Take-Two Interactive,2.66,2.01,0.00,0.41,5.08
175,199,Grand Theft Auto: Vice City Stories,PSP,2006,Action,Take-Two Interactive,1.70,2.02,0.16,1.21,5.08

Sum of Global Sales of the GTA Franchise

In [31]:
gta_games["Global_Sales"].sum()

89.23

Average Number of Global Sales per Year

In [77]:
year = games.groupby("Year").mean()["Global_Sales"]
year

Year
1982     7.810000
1984    28.310000
1985    40.240000
1986     6.510000
1988    12.370000
1989    11.740000
1990    20.610000
1992     7.480000
1993    10.550000
1994     9.300000
1995     5.150000
1996    10.837143
1997     7.776000
1998     7.625714
1999     7.315000
2000     5.845000
2001     5.984000
2002    11.080000
2003     6.075000
2004     8.418000
2005    15.765714
2006    23.043750
2007     6.737857
2008     9.646154
2009    11.689333
2010     8.209412
2011     8.678571
2012     8.652727
2013    11.533750
2014     6.919167
2015     8.932000
2016     4.770000
Name: Global_Sales, dtype: float64

Year with Highest Sales

In [90]:
year[year == year.max()]

Year
1985    40.24
Name: Global_Sales, dtype: float64

Year with Lowest Sales

In [89]:
year[year == year.min()]

Year
2016    4.77
Name: Global_Sales, dtype: float64